// Code generated by go run ./cmd/codegen; DO NOT EDIT.
// Source of truth: api/abi.json

export enum Level {
  TRACE = 0,
  DEBUG = 1,
  INFO = 2,
  WARN = 3,
  ERROR = 4,
  FATAL = 5,
}

export type NativeFns = {
  logger_version: () => string;
  logger_abi_version: () => number;
  logger_create_v1: (configJson: string | null) => unknown;
  logger_create: (configJson: string | null) => unknown;
  logger_create_from_config_file: (configPath: string | null) => unknown;
  logger_log: (
    handle: unknown,
    level: number,
    message: string | null,
    fieldsJson: string | null,
  ) => number;
  logger_log_simple: (
    handle: unknown,
    level: number,
    message: string | null,
  ) => number;
  logger_set_fields: (handle: unknown, fieldsJson: string | null) => number;
  logger_reload_config: (handle: unknown, configJson: string | null) => number;
  logger_flush: (handle: unknown) => number;
  logger_close: (handle: unknown) => number;
  logger_stats: (handle: unknown) => string;
  logger_last_error: (handle: unknown) => string;
  logger_free_string: (s: string | null) => void;
};

/** Bind C ABI symbols from a koffi-loaded library. */
export function bindNative(lib: {
  func: (name: string, result: string, args: string[]) => unknown;
}): NativeFns {
  return {
    logger_version: lib.func(
      "logger_version",
      "str",
      [],
    ) as NativeFns["logger_version"],
    logger_abi_version: lib.func(
      "logger_abi_version",
      "int",
      [],
    ) as NativeFns["logger_abi_version"],
    logger_create_v1: lib.func("logger_create_v1", "void *", [
      "str",
    ]) as NativeFns["logger_create_v1"],
    logger_create: lib.func("logger_create", "void *", [
      "str",
    ]) as NativeFns["logger_create"],
    logger_create_from_config_file: lib.func(
      "logger_create_from_config_file",
      "void *",
      ["str"],
    ) as NativeFns["logger_create_from_config_file"],
    logger_log: lib.func("logger_log", "int", [
      "void *",
      "int",
      "str",
      "str",
    ]) as NativeFns["logger_log"],
    logger_log_simple: lib.func("logger_log_simple", "int", [
      "void *",
      "int",
      "str",
    ]) as NativeFns["logger_log_simple"],
    logger_set_fields: lib.func("logger_set_fields", "int", [
      "void *",
      "str",
    ]) as NativeFns["logger_set_fields"],
    logger_reload_config: lib.func("logger_reload_config", "int", [
      "void *",
      "str",
    ]) as NativeFns["logger_reload_config"],
    logger_flush: lib.func("logger_flush", "int", [
      "void *",
    ]) as NativeFns["logger_flush"],
    logger_close: lib.func("logger_close", "int", [
      "void *",
    ]) as NativeFns["logger_close"],
    logger_stats: lib.func("logger_stats", "str", [
      "void *",
    ]) as NativeFns["logger_stats"],
    logger_last_error: lib.func("logger_last_error", "str", [
      "void *",
    ]) as NativeFns["logger_last_error"],
    logger_free_string: lib.func("logger_free_string", "void", [
      "str",
    ]) as NativeFns["logger_free_string"],
  };
}
